### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [skippyr/river_dreams#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by skippyr** [comment]
I will add one in the next commit.

**Comment by unixorn** [comment]
Cool, thanks. Let me know when you're ready for it to be added by closing this issue or making a PR on  [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins)

**Comment by skippyr** [comment]
I hope the last commit, fix this issue.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/1685

**Comment by skippyr** [comment]
Ok, thanks!
